### ISSUE TITLE
Does not recognize stacking contexts from container queries

### ISSUE THREAD

**Issue by gaberogan** [andreadev-it/stacking-contexts-inspector#11] opened 2024-08-13 17:37 UTC
Does not recognize stacking contexts from [container queries](https://developer.mozilla.org/en-US/docs/Web/CSS/container-type)

**Comment by andreadev-it** [comment] 2024-08-14 21:16
Hi, thank you for the issue!
In theory, the extension should support that, since it should be checking if the property "container-type" is set to either "size" or "inline-size", as per the docs on Stacking Contexts.
Could you share a link or a reproducible example, so that I can troubleshoot this?

**Comment by andreadev-it** [comment] 2024-08-15 10:21
Ok, I saw the issue: the current github version of the extension has that functionality, but it has not been published on the store. I'll do it as soon as I can.
Thank you for pointing it out!

**Comment by andreadev-it** [comment] 2024-08-18 12:08
The published extension on the Chrome Web Store is now updated. Check if you have v. 1.1.16 or newer to see stacking contexts generated by container queries.
Sadly, I still have an issue updating the version of the extension for Firefox, because of the different manifest version and relative code.

I'll close the issue now, if you still have problems after the update, please feel free to reopen it.
Have a nice day

**Closed as completed by andreadev-it** 2024-08-18 12:08 UTC

**Comment by gaberogan** [comment] 2024-08-19 13:58
Thank you! You're the best. Wish I could give you a fiver as a thank you, do you have a donate link?

**Comment by andreadev-it** [comment] 2024-08-20 08:14
I thought about making one, but I haven't gotten around to it yet. I'll probably create it soon, but don't worry, your kind words are already very appreciated!
